package com.example.signin.bean

data class Dept(
    val aliveStatus: Int,
    val ancestors: String,
    val ancestorsTree: String,
    val beginCreateDate: String,
    val beginCreateTime: String,
    val business: Business,
    val children: List<Children>,
    val createBy: String,
    val createTime: String,
    val dateFormat: String,
    val dateType: Int,
    val delFlag: String,
    val deptId: Int,
    val deptName: String,
    val email: String,
    val endCreateDate: String,
    val endCreateTime: String,
    val groupBy: String,
    val leader: String,
    val orderNum: String,
    val params: ParamsXXX,
    val parentId: Int,
    val parentName: String,
    val phone: String,
    val remark: String,
    val searchValue: String,
    val status: String,
    val updateBy: String,
    val updateTime: String,
    val usernames: String
)